# Generated by Django 5.0.5 on 2024-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restuarant_type',
            field=models.CharField(choices=[('IN', 'India'), ('CH', 'Chinese'), ('IT', 'Italain'), ('MX', 'Mexican'), ('GR', 'Greek'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
